name = "testsuite-worker"
main = "src/index.js"
workers_dev = true
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]

[env.development]
ENVIRONMENT = "development"
SUPABASE_URL = "https://iquwsfyqcqyvklbptb.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxdXdzZnlxY29kcXl2a2xicHRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MTMzMzEsImV4cCI6MjA2MTI4OTMzMX0.MnZGYhf4poFzDRpDzaIXq8tEA97tUEkPkNigiDleK8g"



[observability]
enabled = true


# --- Rate Limiter Bindings ---
[[unsafe.bindings]]
  name = "LLM_RATE_LIMITER"
  type = "ratelimit"
  namespace_id = "801"
  simple = { limit = 3, period = 60 }

[[unsafe.bindings]]
  name = "WORKER_RATE_LIMITER"
  type = "ratelimit"
  namespace_id = "800"
  simple = { limit = 10, period = 60 }