name = "testsuite-worker"
main = "src/index.js"
workers_dev = true
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]

[env.development]
ENVIRONMENT = "development"
SUPABASE_URL = "https://iquwsfyqcqyvklbptb.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxdXdzZnlxY29kcXl2a2xicHRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MTMzMzEsImV4cCI6MjA2MTI4OTMzMX0.MnZGYhf4poFzDRpDzaIXq8tEA97tUEkPkNigiDleK8g"



[observability]
enabled = true

[[kv_namespaces]]
binding = "TESTSUITE_KV"
id = "06cb20bef9b747be92ec2c88335a7479"

# --- Rate Limiter Bindings ---
[[unsafe.bindings]]
  name = "FREE_USER_RATE_LIMITER"
  type = "ratelimit"
  namespace_id = "1001" # Reverted to numeric string
  simple = { limit = 4, period = 60 } # Matches 10 in worker code

[[unsafe.bindings]]
  name = "PAID_USER_RATE_LIMITER"
  type = "ratelimit"
  namespace_id = "1002" # Reverted to numeric string
  simple = { limit = 10, period = 60 } # Matches 100 in worker code