name = "testsuite-worker"
main = "src/index.js"
workers_dev = true
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]

[env.development]
vars = { ENVIRONMENT = "development" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "TESTSUITE_KV"
id = "06cb20bef9b747be92ec2c88335a7479"