name = "testsuite-worker"
main = "src/index.js"
workers_dev = true
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]

[env.development]
vars = { ENVIRONMENT = "development" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "TESTSUITE_KV"
id = "06cb20bef9b747be92ec2c88335a7479"

# --- Rate Limiter Bindings ---
[[unsafe.bindings]]
  name = "FREE_USER_RATE_LIMITER"
  type = "ratelimit"
  namespace_id = "1001" # Reverted to numeric string
  simple = { limit = 4, period = 60 } # Matches 10 in worker code

[[unsafe.bindings]]
  name = "PAID_USER_RATE_LIMITER"
  type = "ratelimit"
  namespace_id = "1002" # Reverted to numeric string
  simple = { limit = 10, period = 60 } # Matches 100 in worker code